#!/usr/bin/python3

graph = {}
number_of_nodes = 0
number_of_edges = 0

def add_node(node):
    global graph, number_of_nodes
    if node in graph:
        print("This node already exists")
    else: 
        number_of_nodes += 1
        graph[node] = []

def add_edge(node1, node2):
    global graph, number_of_edges
    if node1 not in graph or node2 not in graph:
        print("Node does not exist")
    else:
        number_of_edges += 1
        graph[node1].append(node2)

import csv
with open('nodes.csv', newline='') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        add_node(row[0])

with open('edges.csv', newline='') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        add_edge(row[0], row[1])

print("Graph in Python:\n" + str(graph))
print("")

def print_graph():
    global graph
    print("Graph as Adjacency List:")
    for node in graph:
        print(node, " -> ", graph[node])

print_graph()
print("")

states_and_degrees_sorted = []

def get_sorted_list_of_degrees():
    global graph
    for node in graph:
        states_and_degrees_sorted.append((node, len(graph[node])))
    states_and_degrees_sorted.sort(key = lambda x: x[1])

def print_states_with_min_degree_and_boundaries():
    global graph, states_and_degrees_sorted
    min_degree = states_and_degrees_sorted[0][1]
    print("Menor quantidades de vizinhos =", min_degree)
    print("Estado(s) com menor quantidades de vizinhos:")
    i = 0
    while states_and_degrees_sorted[i][1] == min_degree:
        state = states_and_degrees_sorted[i][0]
        print(state, '-> ', end = '')
        print(*graph[state], sep = ", ")
        i+=1

def print_states_with_max_degree_and_boundaries():
    global graph, states_and_degrees_sorted
    max_degree = states_and_degrees_sorted[-1][1]
    print("Maior quantidades de vizinhos =", max_degree)
    print("Estado(s) com maior quantidades de vizinhos:")
    i = -1
    while states_and_degrees_sorted[i][1] == max_degree:
        state = states_and_degrees_sorted[i][0]
        print(state, '-> ', end = '')
        print(*graph[state], sep = ", ")
        i-=1

get_sorted_list_of_degrees()

print_states_with_max_degree_and_boundaries()
print("")
print_states_with_min_degree_and_boundaries()
print("")

print(states_and_degrees_sorted)

def print_density():
    global number_of_nodes, number_of_edges
    number_of_undirected_edges = number_of_edges/2
    density = number_of_undirected_edges/number_of_nodes
    print("Densidade =", "{:.2f}".format(density))

print_density()
print("")

degree_frequency = {}

def get_degree_frequency():
    global states_and_degrees_sorted, degree_frequency
    for state_and_degree in states_and_degrees_sorted:
        degree = state_and_degree[1]
        if degree not in degree_frequency:
            degree_frequency[degree] = 1
        else:
            degree_frequency[degree] += 1

def print_degree_frequency():
    global degree_frequency
    print("Frequência de Graus:")
    for degree in degree_frequency:
        print("Grau", degree, "->", degree_frequency[degree], "vezes")    

get_degree_frequency()
print_degree_frequency()
print("")
